- common-styles.html
- etools-upload.html
> Reset invalid state

- bower.json
- etools-upload.html
fixed long filename issue ch[9101]
> fixed long filename issue

- common-mixin.js
- common-styles.js
- etools-upload.js
updated functionality and styles
> code and style updates

- etools-upload.js
added ellipsis if filename is too long
> minor style adjustments

- common-styles.js
- etools-upload.js
> common-styles fix for firefox

- etools-upload.js
> adjusted _showDeleteButton

- etools-upload-multi.js
- etools-upload.js
fixed change button issue and style on etools-upload-multi
> fixed change button issue and style on etools-upload-multi

- etools-upload.js
make the filename container as wide as the file name
> make the filename container as wide as the file name

- README.md
> [ch11836] Update README filesAdd readme

- etools-upload-multi.js
- package.json
[ch17177] File Attachment with long name escapes page
> [ch17177] File Attachment with long name escapes page

- etools-upload-multi.js
- offline/dexie-operations.js
- package.json
> [ch19351]Make sure random temp id is not a valid number & fix spinner

- .gitignore
- etools-upload.js
- package-lock.json
- package.json
[ch19649] etools-upload component to use 'upload' method from etools-ajax package
> [ch19649] etools-upload component to use 'upload' method from etools-ajax package

- package.json
- request-helper-mixin.d.ts
[ch20685] Lint fixes on the d.ts files in common components
> [ch20685] Lint fixes on the d.ts files in common components

- etools-upload.js
[ch24731] Attached files are displayed in the UI with ids
> [ch24731] Attached files are displayed in the UI with ids

- etools-upload-multi.js
- etools-upload.js
- package-lock.json
- package.json
- request-helper-mixin.js
[ch17771] etools-ajax / Show upload progress
> [ch17771] etools-ajax / Show upload progress

- common-styles.js
- package.json
[ch24777] Cancelling on the upload changes the display on upload buttons
> [ch24777] Cancelling on the upload changes the display on upload buttons

- EtoolsUpload.js
- package-lock.json
- package.json
[ch26862] Read Only on file fields should not show Upload File. A simple - should suffice
> [ch26862] Read Only on file fields should not show Upload File. A simple - should suffice

- .npmignore
- package-lock.json
- package.json
> [ch27219]Add .npmignore & update packages

- EtoolsUpload.js
- README.md
- package-lock.json
- package.json
> [ch30724]Fix id displayed after change file

- EtoolsUpload.js
- EtoolsUploadMulti.js
- assets/translations.js
- package-lock.json
- package.json
[ch32471] Upload button translation at language change updates after refresh
> [ch32471] Upload button translation at language change updates after refresh

- EtoolsUpload.js
- package-lock.json
- package.json
[ch33183]  Uploads: File type validation goes away when you hit Save or is incorrectly kept when deleting the file
> [ch33183] Uploads: File type validation goes away when you hit Save or is incorrectly kept when deleting the file
